// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asuqstmhpvtfaxmaknsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzdXFzdG1ocHZ0ZmF4bWFrbnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDkxNjgsImV4cCI6MjA2NDc4NTE2OH0.P6NtVHRpk8IapCziF0yy6WJpU16izJZxWg4bXce619Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);